#!/bin/bash
echo "Welcome To MSI-EC Control Script For MSI Modern 14 B5M"
echo "Written by Olricccc"
echo "Github: https://github.com/Olricccc   "

echo "-------------------------------------------------------------------------------------------"

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

echo "EC Firmware Version: $(sudo cat /sys/devices/platform/msi-ec/fw_version)" 

echo ""

echo "EC Release Date: $(sudo cat /sys/devices/platform/msi-ec/fw_release_date)" 

echo ""

echo "Battery Charge Mode: $(sudo cat /sys/devices/platform/msi-ec/battery_charge_mode)" 

echo ""

echo "Preset : $(sudo cat /sys/devices/platform/msi-ec/preset)"

echo ""

echo "Shift Mode : $(sudo cat /sys/devices/platform/msi-ec/shift_mode)"

echo ""

echo "Cooler Boost: $(sudo cat /sys/devices/platform/msi-ec/cooler_boost)" 

echo ""

echo "Fan Mode: $(sudo cat /sys/devices/platform/msi-ec/fan_mode)" 

echo ""

echo "Windows/Super Button Position: $(sudo cat /sys/devices/platform/msi-ec/win_key)"

echo ""

echo "Fn Button Position: $(sudo cat /sys/devices/platform/msi-ec/fn_key)"

echo ""

echo "Camera : $(sudo cat /sys/devices/platform/msi-ec/webcam)"

echo "-------------------------------------------------------------------------------------------"

echo "Please choose"

echo ""

echo "1-Battery Mode"
echo "2-Preset"
echo "3-Shift Mode"
echo "4-Cooler Boost"
echo "5-Fan Mode"
echo "6-Key Positions"
echo "0-Exit"

read -p "Waiting for user input :" VAR

if [ "$VAR" == "1" ]; then
    clear
    echo "Please choose which battery mode you want to use with numbers"
    echo ""
    echo "1-Minimum (Best for battery. Charge the battery when under 50%, stop at 60%)"
    echo "2-Medium (Balanced. Charge the battery when under 70%, stop at 80%)"
    echo "3-Maximum (Best for mobility. Charge the battery to 100% all the time)"
    echo "0-Go back"

read -p "Waiting for user input:" VARBATT

  
       if [ "$VARBATT" == "0" ]; then
       clear
       bash ./control.sh
  
     elif [ "$VARBATT" == "1" ]; then
       echo "min" > /sys/devices/platform/msi-ec/battery_charge_mode    
       echo "Battery mode switched to Minimum"
       sleep 3
       clear
       bash ./control.sh

     elif [ "$VARBATT" == "2" ]; then
       echo "medium" > /sys/devices/platform/msi-ec/battery_charge_mode
       echo "Battery mode switched to Medium"
       sleep 3
       clear
       bash ./control.sh

     elif [ "$VARBATT" == "3" ]; then
       echo "max" > /sys/devices/platform/msi-ec/battery_charge_mode
       echo "Battery mode switched to Maximum"
              sleep 3
       clear
       bash ./control.sh

    else 
    echo "Please choose correct mode/preset"
                  sleep 3
       clear
       bash ./control.sh
     fi

elif [ "$VAR" == "2" ]; then
    clear
    echo "Please choose which preset you want to use with numbers"
    echo "Your preset choices also can change your shift mode settings."
    echo ""
    echo "1-Super Battery"
    echo "2-Silent"
    echo "3-Balanced"
    echo "4-High Performance"
    echo "0-Go back"

read -p "Waiting for user input: " VARPRESET

     if [ "$VARPRESET" == "0" ]; then
       clear
       bash ./control.sh

     elif [ "$VARPRESET" == "1" ]; then
       echo "super_battery" > /sys/devices/platform/msi-ec/preset
       echo "Switched to Super Battery"
              sleep 3
       clear
       bash ./control.sh

     elif [ "$VARPRESET" == "2" ]; then
       echo "silent" > /sys/devices/platform/msi-ec/preset
       echo "Switched to Silent"
              sleep 3
       clear
       bash ./control.sh

     elif [ "$VARPRESET" == "3" ]; then
       echo "balanced" > /sys/devices/platform/msi-ec/preset
       echo "Switched to Balanced"
              sleep 3
       clear
       bash ./control.sh

     elif [ "$VARPRESET" == "4" ]; then
       echo "high_performance" > /sys/devices/platform/msi-ec/preset
       echo "Switched to High Performance"
              sleep 3
       clear
       bash ./control.sh

    else 
    echo "Please choose correct mode/preset"
                  sleep 3
       clear
       bash ./control.sh
fi

elif [ "$VAR" == "3" ]; then
    clear
    echo "Please choose which shift mode you want to use with numbers"
    echo ""
    echo "1-Overclock"
    echo "2-Balanced"
    echo "3-Eco"
    echo "4-Off (OS decides (I dont know if os decides or not but that's the definiton of this mode))"
    echo "0-Go back"

    read -p "Waiting for user input: " VARSHIFT

    if [ "$VARSHIFT" == "0" ]; then
       clear
       bash ./control.sh
     
     elif [ "$VARSHIFT" == "1" ]; then
       echo "overclock" > /sys/devices/platform/msi-ec/shift_mode
       echo "Switched to Overclock mode"
              sleep 3
       clear
       bash ./control.sh

     elif [ "$VARSHIFT" == "2" ]; then
       echo "balanced" > /sys/devices/platform/msi-ec/shift_mode
       echo "Switched to Balanced mode"
              sleep 3
       clear
       bash ./control.sh

     elif [ "$VARSHIFT" == "3" ]; then
       echo "eco" > /sys/devices/platform/msi-ec/shift_mode
       echo "Switched to Eco mode"
              sleep 3
       clear
       bash ./control.sh

     elif [ "$VARSHIFT" == "4" ]; then
       echo "off" > /sys/devices/platform/msi-ec/shift_mode
       echo "Switched to Off mode"
              sleep 3
       clear
       bash ./control.sh

    else 
    echo "Please choose correct mode/preset"
                  sleep 3
       clear
       bash ./control.sh
     fi

   elif [ "$VAR" == "4" ]; then
    clear
    echo "Please choose if you want to enable Cooler Boost with numbers"
    echo ""
    echo "1-off"
    echo "2-on (DON'T USE IT TOO LONG OR YOUR FANS MAY BE DAMAGED)"
    echo "0-Go back"

    read -p "Waiting for user input:" VARCOOL

     if [ "$VARCOOL" == "0" ]; then
       clear
       bash ./control.sh

     elif [ "$VARCOOL" == "1" ]; then
       echo "off" > /sys/devices/platform/msi-ec/cooler_boost
       echo "Cooler Boost disabled"
              sleep 3
       clear
       bash ./control.sh

     elif [ "$VARCOOL" == "2" ]; then
       echo "on" > /sys/devices/platform/msi-ec/cooler_boost
       echo "Cooler Boost enabled. Be Careful with your fans!"
              sleep 3
       clear
       bash ./control.sh

    else 
    echo "Please choose correct mode/preset"   
                  sleep 3
       clear
       bash ./control.sh
       fi

   elif [ "$VAR" == "5" ]; then
    clear
    echo "Please choose which fan mode you want to use with numbers"
    echo ""
    echo "1-Auto - fan speed adjusts automatically"
    echo "2-Silent - fan speed remains as low as possible"
    echo "3-Advanced - fixed 6-levels fan speed for CPU/GPU (percent)"
    echo "0-Go back"

    read -p "Waiting for user input:" VARFANS

     if [ "$VARFANS" == "0" ]; then
       clear
       bash ./control.sh

     elif [ "$VARFANS" == "1" ]; then
       echo "auto" > /sys/devices/platform/msi-ec/fan_mode
       echo "Fan mode switched to Auto"
              sleep 3
       clear
       bash ./control.sh

     elif [ "$VARFANS" == "2" ]; then
       echo "silent" > /sys/devices/platform/msi-ec/fan_mode
       echo "Fan mode switched to Silent"
              sleep 3
       clear
       bash ./control.sh

    elif [ "$VARFANS" == "3" ]; then
       echo "advanced" > /sys/devices/platform/msi-ec/fan_mode
       echo "Fan mode switched to Advanced"
              sleep 3
       clear
       bash ./control.sh
    else 
    echo "Please choose correct mode/preset"
                  sleep 3
       clear
       bash ./control.sh
    fi

   elif [ "$VAR" == "6" ]; then
    clear
    echo "Please choose your Windows/Fn button layout with numbers"
    echo ""
    echo "1-Windows left/Fn right (Default layout)"
    echo "2-Windows right/Fn left (Fn button switches to Windows button and Windows button switches to Fn button)"
    echo "0-Go back"

    read -p "Waiting for user input:" VARKEYS

          if [ "$VARKEYS" == "0" ]; then
       clear
       bash ./control.sh
     
     elif [ "$VARKEYS" == "1" ]; then
       echo "left" > /sys/devices/platform/msi-ec/win_key
       echo "right" > /sys/devices/platform/msi-ec/fn_key
       echo "Keys switched to Default Layout"
              sleep 3
       clear
       bash ./control.sh

     elif [ "$VARKEYS" == "2" ]; then
       echo "right" > /sys/devices/platform/msi-ec/win_key
       echo "left" > /sys/devices/platform/msi-ec/fn_key
       echo "Keys switched with each other"
              sleep 3
       clear
       bash ./control.sh
    else 
    echo "Please choose correct mode/preset"
                  sleep 3
       clear
       bash ./control.sh

fi

   if [ "$VAR" == "0" ]; then
    exit
   fi

#end of the if
fi
exit